server:
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 30MB
      # 设置总上传的文件大小
      max-request-size: 60MB
  main:
    allow-bean-definition-overriding: true

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.zs.kaoshi.po.**
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
